server:
  port: 9090
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@175.114.237.181:1521:CFIDEV
    username: cfi
    password: vjsem#1004
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
